version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: edutrack_database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - edutrack_data:/var/lib/postgresql/data
    restart: always

volumes:
  edutrack_data:
    driver: local
